server:
  port: 80
  servlet:
    session:
      timeout: Pt30m
    context-path: /

spring:
  application:
    name: shop
  profiles:
    active: pro
  datasource:
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: select 1
  jackson:
    timeZone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      fail-on-empty-beans: false
      write-null-map-values: false
      write-empty-json-arrays: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  freemarker:
    settings: {
      defaultEncoding: UTF-8,
      url_escaping_charset: UTF-8,
      locale: zh_CN,
      tag_syntax: auto_detect,
      whitespace_stripping: true,
      classic_compatible: true,
      number_format: "0.######",
      boolean_format: "true,false",
      datetime_format: "yyyy-MM-dd HH:mm:ss",
      date_format: yyyy-MM-dd,
      time_format: "HH:mm:ss",
      object_wrapper: freemarker.ext.beans.BeansWrapper
    }
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  jpa:
    properties:
      hibernate.search.default.indexBase: ${java.io.tmpdir}/shop/index
      hibernate.search.lucene_version: LUCENE_CURRENT
    #show-sql: true
  messages:
    basename: i18n/admin/messages,i18n/common/messages,i18n/shop/messages
    use-code-as-default-message: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          timeout: 25000
