spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: tiger
  freemarker:
    cache: false
    settings: {
      template_update_delay: 0
    }
  messages:
    cache-duration: Pt0s
  mail:
    host: smtp.example.com
    port: 25
    username: example@163.com
    password: pwd

